### ISSUE TITLE
In Visual C++(VS2022), tinyexpr++ can't be compiled for x64.

### ISSUE THREAD

**Issue by bluenlive** [Blake-Madden/tinyexpr-plusplus#1]
Thanks for your great work.

I am trying to apply tinyexpr++ in my personal notepad2-mod project.
However, it doesn't compile for x64.
It compiles fine for x86.

It fails to compile at the part I have shown below.

```
const std::vector<te_variable> te_parser::m_functions = {
    /* must be in alphabetical order */
    {"abs", static_cast<te_fun1>(std::fabs), TE_PURE},
```

The workarounds I've tried are typecasting to C style, or creating a separate wrapper static function, both of which work fine.

```
const std::vector<te_variable> te_parser::m_functions = {
    /* must be in alphabetical order */
    {"abs", (te_fun1)(std::fabs), TE_PURE},
```

```
static double fabs_wrapper(double n) {
    return fabs(n);
}

const std::vector<te_variable> te_parser::m_functions = {
    /* must be in alphabetical order */
    {"abs", static_cast<te_fun1>(fabs_wrapper), TE_PURE},
```

What are your thoughts on this issue?

**Comment by Blake-Madden** [comment]
I'll check it out, thanks.  The wrapper idea looks good to me. I prefer sticking with `static_cast` since it points out when something is amiss.

**Comment by Blake-Madden** [comment]
Fixed, thanks for the feedback.

**Comment by bluenlive** [comment]
Thank you.
By the way, I noticed that there are a few other functions besides the first mentioned fabs() that have the same problem.
These are the following functions:
std::fabs(n)
std::acos(n)
std::asin(n)
std::atan(n)
std::atan2(n, m)
std::cbrt(n)
std::ceil(n)
std::cos(n)
std::cosh(n)
std::exp(n)
std::floor(n)
std::log(n)
std::log10(n)
std::pow(n, m)
std::sin(n)
std::sinh(n)
std::sqrt(n)
std::tan(n)
std::tanh(n)
std::trunc(n)

Thank you for your job again.

**Comment by bluenlive** [comment]
> Fixed, thanks for the feedback.

Thank you.
By the way, I noticed that there are a few other functions besides the first mentioned fabs() that have the same problem.
These are the following functions:
std::fabs(n)
std::acos(n)
std::asin(n)
std::atan(n)
std::atan2(n, m)
std::cbrt(n)
std::ceil(n)
std::cos(n)
std::cosh(n)
std::exp(n)
std::floor(n)
std::log(n)
std::log10(n)
std::pow(n, m)
std::sin(n)
std::sinh(n)
std::sqrt(n)
std::tan(n)
std::tanh(n)
std::trunc(n)

Thank you for your job again.

**Comment by Blake-Madden** [comment]
I've wrapped all std functions now.

**Comment by bluenlive** [comment]
Sorry for late reply.
The same error occurs for the two rows below.

https://github.com/Blake-Madden/tinyexpr-plusplus/blob/4a7156e8bee6c32ae8fccf76d42afc882f197002/tinyexpr.cpp#L533

https://github.com/Blake-Madden/tinyexpr-plusplus/blob/4a7156e8bee6c32ae8fccf76d42afc882f197002/tinyexpr.cpp#L708

For me, it didn't happen here because I didn't declare TE_POW_FROM_RIGHT, but I suspect it will happen here too.

https://github.com/Blake-Madden/tinyexpr-plusplus/blob/4a7156e8bee6c32ae8fccf76d42afc882f197002/tinyexpr.cpp#L738

Could I use _pow() instead of std::pow() here as well?

**Comment by Blake-Madden** [comment]
Yes.  Sorry, I missed those, but they're fixed now. Thanks!

**Comment by bluenlive** [comment]
Thank you so much!
