### ISSUE TITLE
Using this lib on arduino ?

### ISSUE THREAD

**Issue by Sercurio** [Blake-Madden/tinyexpr-plusplus#3]
Hi,
I'm trying to port my prject from TinyExpr by codeplea to yours for having more operators to use.

But at compilation I have a lot of problems.

Can they be resolved easily ?

![image](https://user-images.githubusercontent.com/38528193/234542063-743c11c4-f5c3-48a4-8454-2b8ee1540fe5.png)

![image](https://user-images.githubusercontent.com/38528193/234542178-924ac987-be78-4960-a811-116f2f2fee59.png)

**Comment by Blake-Madden** [comment]
Are you compiling as C++17?

**Comment by Sercurio** [comment]
Arduino compile with c++11 by default, I change it, fix some errors I can, but it still one error in the library.

![image](https://github.com/Blake-Madden/tinyexpr-plusplus/assets/38528193/00900b27-e751-46b8-a121-7e1511182c31)

**Comment by Blake-Madden** [comment]
Thanks, just uploaded a fix.

**Comment by Sercurio** [comment]
Build sucessful now !

**Comment by Sercurio** [comment]
I need in my program to call the te_parser, result and variables in an interrupt, so I need to declare them as volatile. Setting them as volatile fire others errors.

It is fixable ?

![image](https://github.com/Blake-Madden/tinyexpr-plusplus/assets/38528193/ebb65778-16f6-4768-85e9-9dcbedffc432)

**Comment by Blake-Madden** [comment]
I'll need to sprinkle some `volatile`s throughout the class. I'll check it out...

**Comment by Blake-Madden** [comment]
OK, I just made a few functions volatile. For the rest, you can `const_cast<>` the `te_parser`. I added an "embedded programming" overview discussing this:

https://github.com/Blake-Madden/tinyexpr-plusplus/blob/tinyexpr%2B%2B/Embedded.md

Did this help?

**Comment by Sercurio** [comment]
Yes yes yes ! many thanks !
