### ISSUE TITLE
Volatile support needed

### ISSUE THREAD

**Issue by Blake-Madden** [Blake-Madden/tinyexpr-plusplus#4]
I need in my program to call the te_parser, result and variables in an interrupt, so I need to declare them as volatile. Setting them as volatile fire others errors.

It is fixable ?

![image](https://github.com/Blake-Madden/tinyexpr-plusplus/assets/38528193/ebb65778-16f6-4768-85e9-9dcbedffc432)

_Originally posted by @Sercurio in https://github.com/Blake-Madden/tinyexpr-plusplus/issues/3#issuecomment-1560773503_

**Comment by Sercurio** [comment]
Thanks man !
