### ISSUE TITLE
Using real number and the shift operator together causes a crash.

### ISSUE THREAD

**Issue by bluenlive** [Blake-Madden/tinyexpr-plusplus#5]
- Windows 11
- Compiled with Visual Studio 2022 (17.6.2)

Thank you for your great work.
BTW, using real number and shift operator together causes a crash.
'10<<2' works well.
But '10.1<<2' crashes.

**Comment by Sercurio** [comment]
bitwise operator not purposed to work with double or float (or real)

https://stackoverflow.com/questions/4743115/how-do-i-use-bitwise-operators-on-a-double-on-c

**Comment by Blake-Madden** [comment]
Now you will get NaN as a result call a new function `get_last_error_message()` to get the message.  Before it was throwing this message as an exception, but if you don't catch it from compile/evaluate then that would crash.  Now, I catch it in compile/evaluate and provide the error message.
