### ISSUE TITLE
Provide variable values via callback

### ISSUE THREAD

**Issue by mincequi** [Blake-Madden/tinyexpr-plusplus#7]
Hi there, I stumbled across your lib, which I find pretty interesting for my application.
However, I am missing one feature which some other math expressions parsers seem to offer:
There are variables, which I do not know in advance and I want to register a handler/callback for that which gets the variable name provided and returns an appropriate value.
ExprTk calls this feature **unknown symbol receiver.**
This math parser (bcParserCPP) https://www.mathparsers.com/math-parser-for-cpp/ also has this feature.

Any chance that tinyexpr-plusplus also offers this?

Thanks in advance!

**Comment by Blake-Madden** [comment]
Yes, that should be possible. If I understand correctly, you want pass something with this signature:

`double UnknownSymbolResove(std::string_view unknownVariable)`

If the parser encounters an unknown symbol, it will pass it to the function you provided. If your function returns a valid double value, then the parser uses that and continues on.  If your function returns NaN, then the parser continues on with issuing a syntax error like it normally would. I suppose your function could throw too, but returning NaN would give the parser a change to indicate the position in the formula that the parse occurred.

Would that cover what you need?

**Comment by mincequi** [comment]
Yes, your description nails it.

One thing to notice: this function shall be called again for each evaluation (not just for the compile step).

Note: I just discovered, that ExprTk does not offer this either. I would have to manually populate the variables externally. So, this feature would be exclusively implemented among other open source math parsers.
bcParserCPP is closed source, unfortunately...

Thanks again and looking forward to your consideration!

**Comment by mincequi** [comment]
Another thing to add. Actually, I have the need for a rule engine and there might be some further requirements on the math parser:

Imagine the following TOML config file, that describes what I want to do:
```
[rules]
[rules.enableHeating]
when = "smartMeter1.power > 1900 AND sensor1.temperature < 52"
then = "heating1.powerControl = true"
[rules.disableHeating]
when = "smartMeter1.power < 300 OR sensor1.temperature > 55"
then = "heating1.powerControl = false"
```

So, my idea is, to read and assign properties of objects with the notation "<objectName>.<propertyName>".
Do you believe, that is feasible?

**Comment by Blake-Madden** [comment]
> Another thing to add. Actually, I have the need for a rule engine and there might be some further requirements on the math parser:
> 
> Imagine the following TOML config file, that describes what I want to do:
> 
> ```
> [rules]
> [rules.enableHeating]
> when = "smartMeter1.power > 1900 AND sensor1.temperature < 52"
> then = "heating1.powerControl = true"
> [rules.disableHeating]
> when = "smartMeter1.power < 300 OR sensor1.temperature > 55"
> then = "heating1.powerControl = false"
> ```
> 
> So, my idea is, to read and assign properties of objects with the notation "objectName.propertyName". Do you believe, that is feasible?

This is a separate issue, right? If so, would you mind making another issue report for it. That will help me not get requirements mixed up. Thanks!

**Comment by Blake-Madden** [comment]
> One thing to notice: this function shall be called again for each evaluation (not just for the compile step).

This still needs to be implemented (right now it will set the variable into the parser after it is resolved the first time). Are you needing this because your callback is dynamic, in that it may resolve a symbol differently at different times?  Just trying to come up with a use case for testing and documenting. Thanks!

Otherwise, everything else is implemented. You can check out chapter 11 in the manual if you want to make sure I'm on the right track.

**Comment by mincequi** [comment]
Yes, the value changes dynamically and the expressions has to be evaluated often with different values. Compilation is only needed once, since the expression itself won't change, but the provided variables will change.

**Comment by Blake-Madden** [comment]
> Yes, the value changes dynamically and the expressions has to be evaluated often with different values. Compilation is only needed once, since the expression itself won't change, but the provided variables will change.

OK, this is in there now. By default, resolved variables are cached. However, pass `false` to the second parameter of `set_unknown_symbol_resolver()` and that will cause unknown variables to not be cached and be re-resolved with every eval.
