### ISSUE TITLE
Extensions for rule engine

### ISSUE THREAD

**Issue by mincequi** [Blake-Madden/tinyexpr-plusplus#8]
Actually, I have the need for a rule engine and there might be some further requirements on the math parser:

Imagine the following TOML config file, that describes what I want to do:
```
[rules]
[rules.enableHeating]
when = "smartMeter1.power > 1900 AND sensor1.temperature < 52"
then = "heating1.powerControl = true"
[rules.disableHeating]
when = "smartMeter1.power < 300 OR sensor1.temperature > 55"
then = "heating1.powerControl = false"
```

So, my idea is, to read and assign properties of objects with the notation "objectName.propertyName".
Do you believe, that is feasible?

Thanks in advance.

**Comment by Blake-Madden** [comment]
Just checked in support for periods within functions and var names.

And the `IF` function (if you nest them) should provide the rules logic that you need.

**Comment by mincequi** [comment]
Great to hear. Thanks a lot!
